# Generated by Django 5.0.4 on 2024-05-16 07:12

import Account.models
import cloudinary_storage.storage
import cloudinary_storage.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        
        
        
        migrations.CreateModel(
            name='studentpurchasedcourses',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('student_id', models.CharField(blank=True, max_length=255, null=True)),
                ('course_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post/image'),
        ),
    ]
