# Generated by Django 5.0.4 on 2024-05-16 14:33

import Account.models
import cloudinary_storage.storage
import cloudinary_storage.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_couponpurchase_coursepurchasecoupon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponPurchase',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('coupon_code', models.CharField(blank=True, max_length=255, null=True)),
                ('course_id', models.CharField(blank=True, max_length=255, null=True)),
                ('institution', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('payment_receipt', models.FileField(blank=True, null=True, upload_to=Account.models.coupon_file_path)),
                ('no_of_coupon', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoursePurchaseCoupon',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('coupon_code', models.CharField(blank=True, max_length=255, null=True)),
                ('course_id', models.CharField(blank=True, max_length=255, null=True)),
                ('student_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoursePurchaseRequest',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('client_id', models.CharField(blank=True, max_length=255, null=True)),
                ('course_id', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('MerchantRequestID', models.CharField(blank=True, max_length=255, null=True)),
                ('CheckoutRequestID', models.CharField(blank=True, max_length=255, null=True)),
                ('ResponseCode', models.CharField(blank=True, max_length=255, null=True)),
                ('ResponseDescription', models.CharField(blank=True, max_length=255, null=True)),
                ('CustomerMessage', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LNMOnline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CheckoutRequestID', models.CharField(blank=True, max_length=50, null=True)),
                ('MerchantRequestID', models.CharField(blank=True, max_length=20, null=True)),
                ('ResultCode', models.IntegerField(blank=True, null=True)),
                ('ResultDesc', models.CharField(blank=True, max_length=120, null=True)),
                ('Amount', models.FloatField(blank=True, null=True)),
                ('MpesaReceiptNumber', models.CharField(blank=True, max_length=15, null=True)),
                ('Balance', models.CharField(blank=True, max_length=12, null=True)),
                ('TransactionDate', models.DateTimeField(blank=True, null=True)),
                ('PhoneNumber', models.CharField(blank=True, max_length=13, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=1024)),
                ('file', models.FileField(blank=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='videos/', validators=[cloudinary_storage.validators.validate_video])),
                ('image', models.ImageField(blank=True, upload_to='images/thumbnail')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('audience', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='events',
            name='course_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
