# Generated by Django 5.0.4 on 2024-05-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_couponpurchase_coursepurchasecoupon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='course_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='course_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
